version: '3.1'

services:
  vnode:
    image: yifan:vnode
  scs1:
    working_dir: /scs/1
    image: yifan:scs
    command: scsserver --password 123456 --userconfig userconfig.json --datadir /scs/1 --rpcaddr 0.0.0.0 --rpcport 12345
  scs2:
    working_dir: /scs/2
    image: yifan:scs
    command: scsserver --password 123456 --userconfig userconfig.json --datadir /scs/2 --rpcaddr 0.0.0.0 --rpcport 12345
  scs3:
    working_dir: /scs/3
    image: yifan:scs
    command: scsserver --password 123456 --userconfig userconfig.json --datadir /scs/3 --rpcaddr 0.0.0.0 --rpcport 12345
  scs_monitor:
    working_dir: /scs/monitor
    image: yifan:scs
    command: scsserver --password 123456 --userconfig userconfig.json --datadir /scs/monitor --rpcaddr 0.0.0.0 --rpcport 12345
